
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ACTION_KEYWORD ARRIVAL ARTICLE_CONJUNCTION CONDITIONS CONNECTIVE_WORD CONTEXT_KEYWORD DATE DEPARTURE END_DATE LOCATION LOCATION_MARKER MONEY NUMBER RESOURCE SERVICE START_DATE SYMBOL TIME USERNAMECOMMAND : list_commandlist_command : ACTION_KEYWORD RESOURCE LOCATION_MARKER DEPARTURE LOCATION_MARKER ARRIVAL SYMBOL\n| ACTION_KEYWORD SERVICE CONTEXT_KEYWORD SYMBOLdeparture : DEPARTUREarrival : ARRIVALaction_keyword_rule : ACTION_KEYWORDresource_rule : RESOURCElocation_marker_rule : LOCATION_MARKERcontext_keyword_rule : CONTEXT_KEYWORDservice_rule : SERVICEsymbol_rule : SYMBOL'
    
_lr_action_items = {'ACTION_KEYWORD':([0,],[3,]),'$end':([1,2,9,12,],[0,-1,-3,-2,]),'RESOURCE':([3,],[4,]),'SERVICE':([3,],[5,]),'LOCATION_MARKER':([4,8,],[6,10,]),'CONTEXT_KEYWORD':([5,],[7,]),'DEPARTURE':([6,],[8,]),'SYMBOL':([7,11,],[9,12,]),'ARRIVAL':([10,],[11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'COMMAND':([0,],[1,]),'list_command':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> COMMAND","S'",1,None,None,None),
  ('COMMAND -> list_command','COMMAND',1,'p_command','ABPL.py',133),
  ('list_command -> ACTION_KEYWORD RESOURCE LOCATION_MARKER DEPARTURE LOCATION_MARKER ARRIVAL SYMBOL','list_command',7,'p_list_command','ABPL.py',137),
  ('list_command -> ACTION_KEYWORD SERVICE CONTEXT_KEYWORD SYMBOL','list_command',4,'p_list_command','ABPL.py',138),
  ('departure -> DEPARTURE','departure',1,'p_departure','ABPL.py',147),
  ('arrival -> ARRIVAL','arrival',1,'p_arrival','ABPL.py',151),
  ('action_keyword_rule -> ACTION_KEYWORD','action_keyword_rule',1,'p_action_keyword_rule','ABPL.py',155),
  ('resource_rule -> RESOURCE','resource_rule',1,'p_resource_rule','ABPL.py',159),
  ('location_marker_rule -> LOCATION_MARKER','location_marker_rule',1,'p_location_marker_rule','ABPL.py',163),
  ('context_keyword_rule -> CONTEXT_KEYWORD','context_keyword_rule',1,'p_context_keyword_rule','ABPL.py',167),
  ('service_rule -> SERVICE','service_rule',1,'p_service_rule','ABPL.py',171),
  ('symbol_rule -> SYMBOL','symbol_rule',1,'p_symbol_rule','ABPL.py',175),
]
